
services:
    db:
    # postgress image has been created by someone else. I am just using it.
        image: postgres
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
        # make port 8000 on container correspond to port 8000 on my own computer
        # doing so allows my computer to open up container in web browser
            - "8001:8001"
